### ISSUE TITLE
Error 404 page

### ISSUE THREAD

**Issue by wlexiiii** [proximax-foundry/web-explorer-vuejs#131]
![Image](https://user-images.githubusercontent.com/86057280/197138579-087c270b-7c52-46f6-be2f-68ab4a2865d4.svg)

![Image](https://user-images.githubusercontent.com/86057280/197138873-416925e2-69f3-48f9-baa7-2fa8f3f49887.svg)

![Image](https://user-images.githubusercontent.com/86057280/197138769-1dba022e-1cef-4e8f-9b73-a2098d6bf55f.png)

![Image](https://user-images.githubusercontent.com/86057280/197138807-975192b4-657f-4faf-9525-216862bb1c52.png)

**Comment by SehKeat** [comment]
PR Reference: https://github.com/proximax-foundry/web-explorer-vuejs/pull/162
