### ISSUE TITLE
Transaction Error

### ISSUE THREAD

**Issue by wlexiiii** [proximax-foundry/web-explorer-vuejs#134]
Transaction [4769ED7DEDBE6A9340494F42BCEB410CC3D2563CB247FC4068E503E6C1DB0D9A](https://explorer.xpxsirius.io/#/tx/4769ED7DEDBE6A9340494F42BCEB410CC3D2563CB247FC4068E503E6C1DB0D9A) is an outgoing tx but it is showing incoming (Green arrow)

![Image](https://user-images.githubusercontent.com/86057280/197139665-276af39c-bb1d-4cab-be8e-489006bbcddb.png)

**Comment by SehKeat** [comment]
PR Reference: https://github.com/proximax-foundry/web-explorer-vuejs/pull/147
