### ISSUE TITLE
iOS v15.4 and above not showing over tabs when inner tab was press in transaction details

### ISSUE THREAD

**Issue by SehKeat** [proximax-foundry/web-explorer-vuejs#195]
https://explorer.xpxsirius.io/#/tx/C1FE6677A39DF3D04DF4E1DC05381E1608185A929ED72FCC6CEBEDB26E0F4C20

![Image](https://user-images.githubusercontent.com/97232165/232972729-d240440f-af50-44db-92aa-970d5b579341.png)

![Image](https://user-images.githubusercontent.com/97232165/232972809-e3a887e7-196e-495b-8eab-ba1340fc1e9b.png)

**Comment by shinneng** [comment]
![image](https://github.com/proximax-foundry/web-explorer-vuejs/assets/48303181/8823bcd2-db83-4ed2-a08e-3c0cc692efff)
tested on v16.7.2
