### ISSUE TITLE
Make changes in view multisig accounts

### ISSUE THREAD

**Issue by Ghost-Slime** [proximax-foundry/web-explorer-vuejs#223]
![Image](https://github.com/proximax-foundry/web-explorer-vuejs/assets/85566370/f03128f2-c9f0-48fb-93b8-e323193bdde6)

**Comment by Ghost-Slime** [comment]
PR:
https://github.com/proximax-foundry/web-explorer-vuejs/pull/224

Screenshot:
![Image](https://github.com/proximax-foundry/web-explorer-vuejs/assets/85566370/a7a6e0bc-71f9-4683-8cb5-04346e8dca1a)

**Comment by shinneng** [comment]
resolved in PR #224
